wandb_version: 1

_wandb:
  desc: null
  value:
    python_version: 3.11.9
    cli_version: 0.16.6
    framework: torch
    is_jupyter_run: true
    is_kaggle_kernel: false
    start_time: 1714055561.0
    t:
      1:
      - 1
      - 35
      - 53
      - 55
      - 77
      2:
      - 1
      - 35
      - 53
      - 54
      - 55
      - 77
      3:
      - 13
      - 19
      - 23
      4: 3.11.9
      5: 0.16.6
      8:
      - 1
      - 5
      13: linux-x86_64
labels_type:
  desc: null
  value: linsim
val_ratio:
  desc: null
  value: 0.1
homogeneous:
  desc: null
  value: false
scorelist_size:
  desc: null
  value: 1000
split_ratio:
  desc: null
  value: 0.8
test_ratio:
  desc: null
  value: 0.1
num_neighbors:
  desc: null
  value:
  - 70
  - 55
  - 13
  - 89
  - 85
batch_size:
  desc: null
  value: 1024
train_neg_sampling_ratio:
  desc: null
  value: 224
epochs:
  desc: null
  value: 18
disjoint_train_ratio:
  desc: null
  value: 0.6
lr:
  desc: null
  value: 0.0015308253347932983
stopper_metric:
  desc: null
  value: hit_at_10
stopper_direction:
  desc: null
  value: maximize
stopper_patience:
  desc: null
  value: 5
stopper_frequency:
  desc: null
  value: 1
stopper_relative_delta:
  desc: null
  value: 0.05
gamma:
  desc: null
  value: 1.3
alpha:
  desc: null
  value: 0.42680473078813763
gnn_layer:
  desc: null
  value: ResGatedGraphConv
dropout:
  desc: null
  value: 0.1
norm:
  desc: null
  value: DiffGroupNorm
aggregation:
  desc: null
  value: min
hidden_channels:
  desc: null
  value: 115
num_layers:
  desc: null
  value: 3
attention_heads:
  desc: null
  value: 4
labels:
  desc: null
  value:
    head: genes
    relation: gene_ontology
    tail: go
